name: incident_report
description: A simple Flutter app to report incidents with GPS, media, and prioritization.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  image_picker: ^0.8.7+4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.4.0
  uuid: ^3.0.6
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
